config/routes.rb
Rails.application.routes.draw do
  root to: 'vols#index'
  resources :reservations
  resources :vols
  devise_for :user
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy', as: :signout
    get "/login" => "devise/sessions#new"
    get "/register" => "devise/registrations#new"
  end

  post '/reserve', to: 'reservations#reserver'
  delete '/supprimer', to:'reservations#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vol.rb
class Vol < ApplicationRecord

  def arrival_date(depart, time)
    depart+time*60; # time is in minutes
  end

  def duration_format(min)
    "%02d h %02d m" % [min / 60, min % 60]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:firstname, :lastname, :email, :password, :age)}

  devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:firstname, :lastname, :email, :password, :age, :current_password)}
end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all.where(user_id:current_user.id)
    @user = current_user
  end

  def reserver
    type_classe = params[:type_classe]
    nombre_passagers = params[:places]

    @vol = Vol.find_by(id:params[:id])
    @reservation = Reservation.create(user_id:current_user.id,vol_id:params[:id],classe:type_classe,nombre_places:nombre_passagers,pnr:SecureRandom.hex(3), heure_reservation:DateTime.now)

    reservation_vol = Reservation.all.where(vol_id:params[:id])
    places_prises_business = 0
    places_prises_economie = 0

    reservation_vol.each do |reservation|
        if reservation.classe == 'economie'
          places_prises_economie+= reservation.nombre_places
        else
          places_prises_business+= reservation.nombre_places
        end
    end

    if ((@vol.economy_class_seats - places_prises_economie) < nombre_passagers.to_i && type_classe == 'economie') || ((@vol.business_class_seats - places_prises_business) < nombre_passagers.to_i && type_classe == 'business')
      flash[:alert]="Nombre maximum de places atteint pour votre classe"
      redirect_to controller: 'vols', action: 'show', id: params[:id]
    else
      if @reservation.save
        UserMailer.with(reservation: @reservation,user: current_user,vol:@vol).welcome_email.deliver_later
        redirect_to '/'
      end
    end
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:id, :numeroVol, :idUser, :heureReservation, :classe, :nombrePlaces)
    end
end

app/controllers/vols_controller.rb
class VolsController < ApplicationController
  before_action :set_vol, only: %i[ show edit update destroy ]

  # GET /vols or /vols.json
  def index
    if params[:page].present?
      @vols = Vol.all.page(params[:page])
    else
      @vols = Vol.all.page(1)
    end
  end



  # GET /vols/1 or /vols/1.json
  def show
    
  end

  # GET /vols/new
  def new
    @vol = Vol.new
  end

  # GET /vols/1/edit
  def edit
  end

  # POST /vols or /vols.json
  def create
    @vol = Vol.new(vol_params)

    respond_to do |format|
      if @vol.save
        format.html { redirect_to @vol, notice: "Vol was successfully created." }
        format.json { render :show, status: :created, location: @vol }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vols/1 or /vols/1.json
  def update
    respond_to do |format|
      if @vol.update(vol_params)
        format.html { redirect_to @vol, notice: "Vol was successfully updated." }
        format.json { render :show, status: :ok, location: @vol }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vols/1 or /vols/1.json
  def destroy
    @vol.destroy
    respond_to do |format|
      format.html { redirect_to vols_url, notice: "Vol was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vol
      @vol = Vol.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vol_params
      params.require(:vol).permit(:number, :departure_airport, :arrival_airport, :business_class_seats, :economy_class_seats, :departure_date, :duration)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/vols_helper.rb
module VolsHelper
end

app/views/layouts/_header.erb
<div class="header">
  <h1 class="title">Planeline</h1>

  <nav class="navigation">
    <ul>
      <li class="nav-links"><a href="/vols">
        <% if user_signed_in? %>
          Réserver un vol
        <% else %>
          Liste des vols
        <% end %>
          </a></li>
      <% if user_signed_in? %>
        <li class="nav-links"><a href="/reservations">Mes réservations</a></li>
        <li class="nav-links"><a href="/logout">Déconnexion</a></li>
      <% else %>
        <li class="nav-links"><a href="/login">Se connecter</a></li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;400;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/header" %>
  <div class="container">
    <% if alert %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <% if notice %>
      <div class="alert alert-success alert-dismissible fade show" role="notice">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id %>
  </div>

  <div class="field">
    <%= form.label :numeroVol %>
    <%= form.number_field :numeroVol %>
  </div>

  <div class="field">
    <%= form.label :idUser %>
    <%= form.number_field :idUser %>
  </div>

  <div class="field">
    <%= form.label :heureReservation %>
    <%= form.datetime_select :heureReservation %>
  </div>

  <div class="field">
    <%= form.label :classe %>
    <%= form.text_field :classe %>
  </div>

  <div class="field">
    <%= form.label :nombrePlaces %>
    <%= form.number_field :nombrePlaces %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h2>Mon profil</h2>

<hr>

<div class="row">
  <div class="col-9 row">
    <div class="d-flex align-items-center">
      <h3 class="me-4">Mes réservations</h3>
      <%= link_to 'Faire une reservation', '/', class: 'btn btn-primary' %>
    </div>
    <% @reservations.each do |reservation| %>
      <div class="reserv-card col-3 m-3">
        <div class="card-head">
          <img src="https://cdn.radiofrance.fr/s3/cruiser-production/2020/03/4846b9fe-69d4-491a-b89b-b2a0a8da76db/1136_avion_gettyimages-1137268547.jpg">
        </div>
        <div class="card-body">
          <% vol = Vol.find(reservation.vol_id) %>
          <p class="airport"><%= vol.departure_airport %> - <%= vol.arrival_airport %></p>
          <p><%= vol.departure_date.strftime("%d/%m/%y") %></p>
          <p><%= reservation.nombre_places%> place(s) <%= reservation.classe.capitalize() %></p>
          <p class="b"><%= reservation.pnr.upcase %></p>
          <a href="/reservations/<%= reservation.id %>" class="btn btn-primary mb-2">Voir</a>
          <%= button_to "Supprimer", {:controller => "reservations", :action => "destroy", :id => reservation.id} , :method => :delete, class: "btn btn-danger submit"%>

        </div>
      </div>

    <% end %>

  </div>
  <div class="col-3">
    <div class="user-info">
      <h3 class="mb-4">Mes informations</h3>
      <p id="name"><span class="u">Name: </span> <%= current_user.lastname %></p>
      <p id="firstname"><span class="u">Firstname: </span> <%= current_user.firstname %></p>
      <p id="age"><span class="u">Age: </span> <%= current_user.age %></p>
      <%= link_to 'Modifier mes informations', edit_user_registration_path %>
    </div>

  </div>
</div>

<br>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<% vol = Vol.find(@reservation.vol_id) %>
<% user = User.find(@reservation.user_id) %>

<div class="d-flex">
  <a href="/reservations" class="btn btn-secondary mb-2 me-2">Retour</a>
  <%= button_to "Supprimer", {:controller => "reservations", :action => "destroy", :id => @reservation.id} , :method => :delete, class: "btn btn-danger submit"%>
</div>

<h2>Réservation <%= @reservation.pnr.upcase() %></h2>


<div class="row">
  <div class="col-6">

    <div class="depart d-flex flex-column mt-4 mb-2">
      <p class="mb-1"><%= vol.departure_date.strftime("%d/%m/%Y") %></p>
      <div class="d-flex">
        <p id="airport"><%= vol.departure_airport %></p>
        <p id="time-d"><%= vol.departure_date.strftime("%H:%M") %></p>
      </div>
    </div>

    <div class="path" style="height: 15vh;"></div>

    <p class="dur my-2"><%= vol.duration_format(vol.duration) %></p>

    <div class="path" style="height: 15vh;"></div>

    <div class="arrive d-flex flex-column mt-2 mb-1">
      <p class="mb-1"><%= vol.arrival_date(vol.departure_date, vol.duration).strftime("%d/%m/%Y") %></p>
      <div class="d-flex">
        <p id="airport"><%= vol.arrival_airport %></p>
        <p id="time-d"><%= vol.arrival_date(vol.departure_date, vol.duration).strftime("%H:%M") %></p>
      </div>
    </div>
  </div>
  <div class="col-6">
    <p>Réservation faites le : <%= @reservation.heure_reservation.strftime("%d/%m/%Y") %> à <%= @reservation.heure_reservation.strftime("%H:%M") %></p>
    <p>Nombre de place(s) : <%= @reservation.nombre_places %> <%= @reservation.classe.capitalize() %></p>
    <p>Nom d'enregistrement: <%= user.firstname %> <%= user.lastname %></p>
  </div>
</div>

app/views/vols/_form.html.erb
<%= form_with(model: vol) do |form| %>
  <% if vol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vol.errors.count, "error") %> prohibited this vol from being saved:</h2>

      <ul>
        <% vol.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :departure_airport %>
    <%= form.text_field :departure_airport %>
  </div>

  <div class="field">
    <%= form.label :arrival_airport %>
    <%= form.text_field :arrival_airport %>
  </div>

  <div class="field">
    <%= form.label :business_class_seats %>
    <%= form.number_field :business_class_seats %>
  </div>

  <div class="field">
    <%= form.label :economy_class_seats %>
    <%= form.number_field :economy_class_seats %>
  </div>

  <div class="field">
    <%= form.label :departure_date %>
    <%= form.datetime_select :departure_date %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vols/edit.html.erb
<h1>Editing Vol</h1>

<%= render 'form', vol: @vol %>

<%= link_to 'Show', @vol %> |
<%= link_to 'Back', vols_path %>

app/views/vols/index.html.erb
<h2>Trouvez le vol qui vous correspond !</h2>
<% if !user_signed_in? %>
  <p class="p">Connectez vous pour réserver un vol !</p>
<% end %>

<hr style="margin: 1em 0">

<%= paginate @vols %>


<div class="list">
  <% if @vols.length == 0 %>

      <h3>Aucun vol trouvé !</h3>

  <% else %>
    <% @vols.each do |vol| %>
      <% if vol.departure_date.future? %>
        <div class="flight-card">

          <div class="departure">
            <p class="date"><%= vol.departure_date.strftime("%d/%m/%y") %></p>
            <p class="time"><%= vol.departure_date.strftime("%H:%M") %></p>
            <p class="airport"><%= vol.departure_airport %></p>
          </div>

          <p class="duration">Durée <%= vol.duration_format(vol.duration) %></p>

          <div class="arrival">
            <p class="date"><%= vol.arrival_date(vol.departure_date, vol.duration).strftime("%d/%m/%y") %></p>
            <p class="time"><%= vol.arrival_date(vol.departure_date, vol.duration).strftime("%H:%M"); %></p>
            <p class="airport"><%= vol.arrival_airport %></p>
          </div>

          <div class="info">
            <p>Numéro de vol</p>
            <p class="id"><%= vol.number %></p>
          </div>
          <% if user_signed_in? %>
            <%= button_to "Reserver", {:controller => "vols", :action => "show", :id => vol.id} , method: :get, class: "btn btn-success submit"%>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>


</div>
<br>
<%= paginate @vols %>

app/views/vols/new.html.erb
<h1>New Vol</h1>

<%= render 'form', vol: @vol %>

<%= link_to 'Back', vols_path %>

app/views/vols/show.html.erb
<%= form_with url: {:controller => "reservations", :action => "reserver", :id => @vol.id}, method: :post do |form| %>

  <h3 class="mb-5">Réservation pour le vol  <%= @vol.number %></h3>

  <div class="d-flex align-items-center">
    <%= form.label :places, "Nombre de place(s): ", class: "form-check-label me-2" %>
    <%= form.number_field :places, in: 1.0..99.0, step: 1, class: "form-control" %>
  </div>

  <div class="d-flex">
    <%= form.radio_button :type_classe, "economie", class: "form-check-input me-2", :required => true , checked: true %>
    <%= form.label :type_classe_eco, "Economie", class: 'form-check-label me-1' %>
    <%= form.radio_button :type_classe, "business", class: "form-check-input me-2" %>
    <%= form.label :type_classe_business, "Business", class: 'form-check-label me-1' %>
  </div>

  <div class="d-flex mt-5">
    <%= form.submit "Valider",class: "btn btn-success submit me-2" %>
    <%= link_to 'Retour', vols_path, class: "btn btn-secondary" %>

  </div>
<% end %>